using CommandLine;

namespace ConvertLabelsToPdf.CommandLineUtils
{
    internal class Options
    {
        [Option(
            's',
            "sourceDirectory",
            Default = null,
            HelpText = "States for source directory path to be looked up for image files in order to convert them into pdf file.",
            Required = true)]
        public string SourceDirectory { get; set; }

        [Option(
            't',
            "targetDirectory",
            Default = null,
            HelpText = "If specified, states for target directory path, where converted pdf file will be put. Otherwise, generated file will be put in source directory.",
            Required = false)]
        public string TargetDirectory { get; set; }

        [Option(
            'f',
            "fileName",
            Default = null,
            HelpText = "If specified, states for file name of the generated pdf. Otherwise, will be autogenerated",
            Required = false)]

        public string TargetPdfFileName { get; set; }
    }
}